namespace CreditCardApplication.Application.Applications;

public sealed record CreateCardApplicationRequest(
    int CustomerId,
    int CardTypeId,
    decimal RequestedLimit,
    string DeliveryAddress = "Kayıtlı müşteri adresi",
    string StatementPreference = "Email",
    string DeliveryMethod = "RegisteredAddress",
    string? DeliveryCity = null,
    string? DeliveryDistrict = null,
    string? DeliveryNeighborhood = null,
    string? DeliveryRecipientName = null,
    string? DeliveryPhone = null,
    string? DeliveryBranch = null,
    bool ContactlessEnabled = true,
    bool InternetShoppingEnabled = true,
    string? ApplicationNote = null,
    int StatementDay = 14,
    bool AutomaticLimitIncreaseEnabled = false,
    bool DuplicateWarningAcknowledged = false,
    bool IdentityDocumentConfirmed = false,
    bool IncomeDocumentConfirmed = false,
    bool ResidenceDocumentConfirmed = false);

public sealed record EvaluateCardApplicationRequest(
    string Decision,
    decimal? ApprovedLimit,
    string? Note);

public sealed record ResubmitCardApplicationRequest(
    int CardTypeId,
    decimal RequestedLimit,
    string DeliveryAddress = "Kayıtlı müşteri adresi",
    string StatementPreference = "Email",
    string DeliveryMethod = "RegisteredAddress",
    string? DeliveryCity = null,
    string? DeliveryDistrict = null,
    string? DeliveryNeighborhood = null,
    string? DeliveryRecipientName = null,
    string? DeliveryPhone = null,
    string? DeliveryBranch = null,
    bool ContactlessEnabled = true,
    bool InternetShoppingEnabled = true,
    string? ApplicationNote = null,
    int StatementDay = 14,
    bool AutomaticLimitIncreaseEnabled = false,
    bool IdentityDocumentConfirmed = false,
    bool IncomeDocumentConfirmed = false,
    bool ResidenceDocumentConfirmed = false);

public sealed record CardTypeResponse(
    int Id,
    string Name,
    string ProductName,
    string Network,
    string Bin,
    decimal? MinimumLimit,
    decimal? MaximumLimit,
    string ProductDescription,
    string AnnualFee,
    IReadOnlyList<string> Benefits);

public sealed record CardApplicationResponse(
    int Id,
    string ApplicationNumber,
    int CustomerId,
    string CustomerNumber,
    string CustomerFullName,
    string CustomerNationalIdentityNumber,
    string CustomerPhoneCountryCode,
    string CustomerPhoneNumber,
    string CustomerEmailAddress,
    decimal CustomerMonthlyNetIncome,
    decimal CustomerOtherBankTotalCardLimit,
    int CustomerCreditScore,
    int CardTypeId,
    string CardTypeName,
    decimal RequestedLimit,
    decimal AvailableLimit,
    string DeliveryMethod,
    string DeliveryAddress,
    string? DeliveryCity,
    string? DeliveryDistrict,
    string? DeliveryNeighborhood,
    string? DeliveryRecipientName,
    string? DeliveryPhone,
    string? DeliveryBranch,
    string StatementPreference,
    int StatementDay,
    bool ContactlessEnabled,
    bool InternetShoppingEnabled,
    bool AutomaticLimitIncreaseEnabled,
    bool IdentityDocumentConfirmed,
    bool IncomeDocumentConfirmed,
    bool ResidenceDocumentConfirmed,
    int PreAssessmentScore,
    string PreAssessmentRiskLevel,
    string PreAssessmentRecommendation,
    string? ApplicationNote,
    string Status,
    DateTime CreatedAtUtc,
    bool IsEvaluationBlocked = false,
    int? AssignedOfficerUserId = null,
    string? AssignedOfficerName = null,
    DateTime? AssignedAtUtc = null,
    bool RequiresSecondApproval = false,
    string WorkflowStage = "ManagerReview",
    int? FirstApprovedByUserId = null,
    string? FirstApproverName = null,
    DateTime? FirstApprovedAtUtc = null,
    string ApprovalPolicy = "100.000 TL üzeri veya yüksek riskli başvurularda iki farklı müdür onayı gerekir.",
    bool AutoAssignmentCompleted = false,
    string? LastAssignmentReason = null,
    int EscalationLevel = 0,
    string? CancellationReason = null,
    DateTime? CancelledAtUtc = null,
    string? CancelledByName = null);

public sealed record ApplicationHistoryResponse(
    string? PreviousStatus,
    string NewStatus,
    string? Description,
    string ChangedBy,
    DateTime ChangedAtUtc);

public sealed record CardApplicationDetailResponse(
    CardApplicationResponse Application,
    decimal? ApprovedLimit,
    string? EvaluationNote,
    int? CreditCardId,
    IReadOnlyList<ApplicationHistoryResponse> History);
