import { Component, OnInit, signal } from '@angular/core';
import { DecimalPipe } from '@angular/common';
import { FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { CardApplication } from '../card-application.models';
import { CardApplicationApiService } from '../card-application-api.service';

@Component({
  selector: 'app-application-review', imports: [ReactiveFormsModule, DecimalPipe, RouterLink],
  template: `<section class="page"><p>DEĞERLENDİRME KUYRUĞU</p><h1>Bekleyen Başvurular</h1><span>Karar bekleyen başvuruları ayrıntılarıyla inceleyip sonuçlandırın.</span>@if(error()){<div class="error">{{error()}}</div>}<div class="card"><table><thead><tr><th>Başvuru</th><th>Müşteri</th><th>Kart</th><th>Talep</th><th></th></tr></thead><tbody>@for(item of applications();track item.id){<tr><td><a [routerLink]="['/manager/applications', item.id]">{{item.applicationNumber}}</a></td><td>{{item.customerFullName}}</td><td>{{item.cardTypeName}}</td><td>{{item.requestedLimit|number:'1.2-2'}} TL</td><td><button (click)="select(item)">Değerlendir</button></td></tr>}@empty{<tr><td colspan="5" class="empty">Bekleyen başvuru yok.</td></tr>}</tbody></table></div>@if(selected();as item){<div class="overlay" role="presentation"><form class="modal" role="dialog" aria-modal="true" aria-labelledby="evaluation-title" [formGroup]="form" (ngSubmit)="save()"><p>MÜDÜR KARARI</p><h2 id="evaluation-title">{{item.applicationNumber}}</h2><div class="application-summary"><span>{{item.customerFullName}}</span><b>{{item.cardTypeName}} · {{item.requestedLimit|number:'1.2-2'}} TL</b></div><label>Karar<select formControlName="decision"><option value="Approved">Onayla</option><option value="Rejected">Reddet</option><option value="Revision">Revizyona gönder</option></select></label><label>Onaylanan limit<input type="number" formControlName="approvedLimit"></label><label>Açıklama<textarea rows="4" formControlName="note"></textarea></label><div class="modal-actions"><button type="button" class="secondary" (click)="selected.set(null)">Vazgeç</button><button type="submit">Kararı kaydet</button></div></form></div>}</section>`,
  styles: `.page{padding:2rem}.page>p,.modal>p{color:#b88918;font-weight:700;font-size:.75rem;letter-spacing:.08em}.page>span{color:#627d98}h1{color:#102a43}.card{background:#fff;border:1px solid #d9e2ec;border-radius:10px;padding:1.25rem;margin-top:1rem}table{width:100%;border-collapse:collapse}th,td{padding:.8rem;border-bottom:1px solid #edf2f7;text-align:left}th{color:#486581}label{display:grid;gap:.4rem;font-weight:600}input,select,textarea{padding:.65rem;border:1px solid #bcccdc;border-radius:5px}button{background:#b88918;color:#fff;border:0;border-radius:5px;padding:.6rem .85rem;margin-right:.5rem;cursor:pointer}.secondary{background:#e9eef3;color:#243b53}.error{color:#b42318}.empty{text-align:center;color:#627d98}.overlay{position:fixed;inset:0;background:#102a43a6;display:grid;place-items:center;padding:1rem;z-index:50}.modal{width:min(580px,100%);background:#fff;border-radius:12px;box-shadow:0 24px 60px #102a4366;padding:1.5rem;display:grid;gap:1rem}.modal h2{margin:0;color:#102a43}.application-summary{display:flex;justify-content:space-between;background:#f0f4f8;padding:1rem;border-radius:7px;color:#486581}.modal-actions{display:flex;justify-content:flex-end;margin-top:.5rem}`
})
export class ApplicationReview implements OnInit {
  protected readonly applications = signal<CardApplication[]>([]); protected readonly selected = signal<CardApplication | null>(null); protected readonly error = signal('');
  protected readonly form = new FormGroup({decision:new FormControl<'Approved'|'Rejected'|'Revision'>('Approved',{nonNullable:true}),approvedLimit:new FormControl<number|null>(null),note:new FormControl<string|null>(null)});
  constructor(private readonly api: CardApplicationApiService) {} ngOnInit(): void { this.load(); }
  protected select(item: CardApplication): void { this.selected.set(item); this.form.setValue({decision:'Approved',approvedLimit:item.requestedLimit,note:null}); }
  protected save(): void { const item=this.selected(); if(!item)return; this.api.evaluate(item.id,this.form.getRawValue()).subscribe({next:()=>{this.selected.set(null);this.load();},error:r=>this.error.set(r.error?.detail??'Karar kaydedilemedi.')}); }
  private load(): void { this.api.getPending().subscribe({next:items=>this.applications.set(items),error:()=>this.error.set('Başvuru kuyruğu yüklenemedi.')}); }
}
